=== YunTianHan/Autumn-2023-Database-CourseWork/Autumn 2023 Database CourseWork/coursework1_202118010418/6_Structure.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT eCorporation (Country*)>
<!ELEMENT Country (Organization*)>
<!ATTLIST Country   
	name	CDATA	#REQUIRED
>
<!ELEMENT Organization (Name, Website, Description, Founded, Industry, NumberEmployees, Employees*)>
<!ATTLIST Organization   
	OrganizationID	CDATA	#REQUIRED
>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Website (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Founded (#PCDATA)>
<!ELEMENT Industry (#PCDATA)>
<!ELEMENT NumberEmployees (#PCDATA)>
<!ELEMENT Employees (FirstName, LastName, Sex, Email, Phone, BirthDate, JobTitle)>
<!ATTLIST Employees   
	UserID	CDATA	#REQUIRED
>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Sex (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT BirthDate (#PCDATA)>
<!ELEMENT JobTitle (#PCDATA)>

=== YunTianHan/Autumn-2023-Database-CourseWork/Autumn 2023 Database CourseWork/coursework1_202118010418/5_Output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE eCorporation SYSTEM "6_Structure.dtd">
<eCorporation>
	<Country name="Anguilla">
		<Organization OrganizationID="BA6Cd9Dae2Efd62">
			<Name>Good Ltd</Name>
			<Website>http://duffy.com/</Website>
			<Description>Reverse-engineered composite moratorium</Description>
			<Founded>1971</Founded>
			<Industry>Consumer Services</Industry>
			<NumberEmployees>4292</NumberEmployees>
			<Employees UserID="dade3452F0c32FD">
				<FirstName>Jonathon</FirstName>
				<LastName>Atkinson</LastName>
				<Sex>Male</Sex>
				<Email>gailfrench@example.net</Email>
				<Phone>874-037-2032</Phone>
				<BirthDate>7/19/1987</BirthDate>
				<JobTitle>Psychologist, forensic</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Australia">
		<Organization OrganizationID="7Cb3AeFcE4Ba31e">
			<Name>Rivas Group</Name>
			<Website>https://hebert.org/</Website>
			<Description>Open-architected well-modulated capacity</Description>
			<Founded>1998</Founded>
			<Industry>Logistics / Procurement</Industry>
			<NumberEmployees>4155</NumberEmployees>
			<Employees UserID="5bC87340799FBD0">
				<FirstName>Jean</FirstName>
				<LastName>Ritter</LastName>
				<Sex>Female</Sex>
				<Email>kristina76@example.com</Email>
				<Phone>(954)060-1066</Phone>
				<BirthDate>8/6/1985</BirthDate>
				<JobTitle>Financial trader</JobTitle>
			</Employees>
			<Employees UserID="2EFC6A4e77FaEaC">
				<FirstName>Ricardo</FirstName>
				<LastName>Hinton</LastName>
				<Sex>Male</Sex>
				<Email>wyattbishop@example.com</Email>
				<Phone>447-699-8612</Phone>
				<BirthDate>3/26/1974</BirthDate>
				<JobTitle>Hydrogeologist</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Bahamas">
		<Organization OrganizationID="cC757116fe1C085">
			<Name>Henry-Thompson</Name>
			<Website>http://morse.net/</Website>
			<Description>Face-to-face well-modulated customer loyalty</Description>
			<Founded>1992</Founded>
			<Industry>Primary / Secondary Education</Industry>
			<NumberEmployees>4914</NumberEmployees>
			<Employees UserID="5d2feAfbdCAA6B5">
				<FirstName>Isaiah</FirstName>
				<LastName>Camacho</LastName>
				<Sex>Female</Sex>
				<Email>jimblake@example.org</Email>
				<Phone>536-544-3367</Phone>
				<BirthDate>4/7/1966</BirthDate>
				<JobTitle>Food technologist</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Belarus">
		<Organization OrganizationID="6883A965c7b68F7">
			<Name>Hahn PLC</Name>
			<Website>http://newman.com/</Website>
			<Description>Organic logistical leverage</Description>
			<Founded>2012</Founded>
			<Industry>Electrical / Electronic Manufacturing</Industry>
			<NumberEmployees>3715</NumberEmployees>
			<Employees UserID="66F096D36Ebae11">
				<FirstName>Judy</FirstName>
				<LastName>Buckley</LastName>
				<Sex>Male</Sex>
				<Email>irosales@example.net</Email>
				<Phone>001-654-5283</Phone>
				<BirthDate>7/28/1963</BirthDate>
				<JobTitle>Art gallery manager</JobTitle>
			</Employees>
			<Employees UserID="F0fE2faAd78F8b5">
				<FirstName>Norman</FirstName>
				<LastName>Weber</LastName>
				<Sex>Male</Sex>
				<Email>mconrad@example.com</Email>
				<Phone>223-002-0429</Phone>
				<BirthDate>5/21/1987</BirthDate>
				<JobTitle>Gaffer</JobTitle>
			</Employees>
			<Employees UserID="bff9853aFAeF772">
				<FirstName>Douglas</FirstName>
				<LastName>Reese</LastName>
				<Sex>Female</Sex>
				<Email>nixonvanessa@example.net</Email>
				<Phone>834-660-9864</Phone>
				<BirthDate>11/11/1969</BirthDate>
				<JobTitle>Higher education lecturer</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Belgium">
		<Organization OrganizationID="5Ec4C272bCf085c">
			<Name>Robbins-Cummings</Name>
			<Website>http://donaldson-wilkins.com/</Website>
			<Description>Organic non-volatile hierarchy</Description>
			<Founded>1991</Founded>
			<Industry>Pharmaceuticals</Industry>
			<NumberEmployees>5038</NumberEmployees>
		</Organization>
	</Country>
	<Country name="Benin">
		<Organization OrganizationID="235fdEFE2cfDa5F">
			<Name>Brock-Blackwell</Name>
			<Website>http://www.small.com/</Website>
			<Description>Secured foreground emulation</Description>
			<Founded>1986</Founded>
			<Industry>Online Publishing</Industry>
			<NumberEmployees>7034</NumberEmployees>
			<Employees UserID="E47FB71DD9ACCd9">
				<FirstName>Joshua</FirstName>
				<LastName>Sweeney</LastName>
				<Sex>Male</Sex>
				<Email>daisymcgee@example.net</Email>
				<Phone>875-994-2535</Phone>
				<BirthDate>7/28/1974</BirthDate>
				<JobTitle>Education officer, museum</JobTitle>
			</Employees>
			<Employees UserID="88F7B33d2bcf9f5">
				<FirstName>Shelby</FirstName>
				<LastName>Terrell</LastName>
				<Sex>Male</Sex>
				<Email>elijah57@example.net</Email>
				<Phone>084-906-7358</Phone>
				<BirthDate>10/26/1985</BirthDate>
				<JobTitle>Games developer</JobTitle>
			</Employees>
		</Organization>
		<Organization OrganizationID="dfcA1c84AdB61Ac">
			<Name>Mccall-Holmes</Name>
			<Website>http://www.dean.com/</Website>
			<Description>Object-based value-added database</Description>
			<Founded>2009</Founded>
			<Industry>Legal Services</Industry>
			<NumberEmployees>696</NumberEmployees>
		</Organization>
		<Organization OrganizationID="7ABc3c7ecA03B34">
			<Name>Sampson-Griffith</Name>
			<Website>http://hendricks.org/</Website>
			<Description>Multi-layered composite paradigm</Description>
			<Founded>1972</Founded>
			<Industry>Textiles</Industry>
			<NumberEmployees>3881</NumberEmployees>
			<Employees UserID="d181FFB7d3E68bb">
				<FirstName>Xavier</FirstName>
				<LastName>Cole</LastName>
				<Sex>Male</Sex>
				<Email>nicolas90@example.org</Email>
				<Phone>816-425-9975</Phone>
				<BirthDate>11/29/1978</BirthDate>
				<JobTitle>Financial planner</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Bolivia">
		<Organization OrganizationID="4D4d7E18321eaeC">
			<Name>Pineda-Cox</Name>
			<Website>http://aguilar.org/</Website>
			<Description>Fundamental asynchronous capability</Description>
			<Founded>2010</Founded>
			<Industry>Human Resources / HR</Industry>
			<NumberEmployees>1312</NumberEmployees>
		</Organization>
	</Country>
	<Country name="Botswana">
		<Organization OrganizationID="ba179F19F7925f5">
			<Name>Branch-Mann</Name>
			<Website>http://www.lozano.com/</Website>
			<Description>Adaptive intangible frame</Description>
			<Founded>1999</Founded>
			<Industry>Architecture / Planning</Industry>
			<NumberEmployees>7961</NumberEmployees>
			<Employees UserID="AdEd6cfD85DeC46">
				<FirstName>Jermaine</FirstName>
				<LastName>Reid</LastName>
				<Sex>Female</Sex>
				<Email>vpaul@example.com</Email>
				<Phone>(742)214-8691</Phone>
				<BirthDate>8/18/1974</BirthDate>
				<JobTitle>Newspaper journalist</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Bouvet Island (Bouvetoya)">
		<Organization OrganizationID="AE61b8Ffebbc476">
			<Name>Kidd Group</Name>
			<Website>http://www.lyons.com/</Website>
			<Description>Proactive foreground paradigm</Description>
			<Founded>2001</Founded>
			<Industry>Primary / Secondary Education</Industry>
			<NumberEmployees>7473</NumberEmployees>
			<Employees UserID="DbeAb8CcdfeFC2c">
				<FirstName>Kristine</FirstName>
				<LastName>Travis</LastName>
				<Sex>Male</Sex>
				<Email>bthompson@example.com</Email>
				<Phone>277-609-7938</Phone>
				<BirthDate>7/2/1992</BirthDate>
				<JobTitle>Homeopath</JobTitle>
			</Employees>
			<Employees UserID="cBbBcA0FCA3C4Bc">
				<FirstName>Randy</FirstName>
				<LastName>Barnes</LastName>
				<Sex>Male</Sex>
				<Email>huangbill@example.org</Email>
				<Phone>960-629-7214</Phone>
				<BirthDate>12/30/1977</BirthDate>
				<JobTitle>Outdoor activities/education manager</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Brazil">
		<Organization OrganizationID="055ffEfB2Dd95B0">
			<Name>Riley Ltd</Name>
			<Website>http://wiley.com/</Website>
			<Description>Optional exuding superstructure</Description>
			<Founded>1986</Founded>
			<Industry>Textiles</Industry>
			<NumberEmployees>9315</NumberEmployees>
			<Employees UserID="b6a35de5CB6fc25">
				<FirstName>Cynthia</FirstName>
				<LastName>Wiggins</LastName>
				<Sex>Female</Sex>
				<Email>rosariodave@example.org</Email>
				<Phone>(110)858-7190</Phone>
				<BirthDate>1/27/1984</BirthDate>
				<JobTitle>Outdoor activities/education manager</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Burundi">
		<Organization OrganizationID="F4Dc1417BC6cb8f">
			<Name>Gilbert-Simon</Name>
			<Website>https://www.bradford.biz/</Website>
			<Description>Grass-roots radical parallelism</Description>
			<Founded>1973</Founded>
			<Industry>Newspapers / Journalism</Industry>
			<NumberEmployees>1927</NumberEmployees>
			<Employees UserID="88473e15D5c3cD0">
				<FirstName>Jared</FirstName>
				<LastName>Mitchell</LastName>
				<Sex>Female</Sex>
				<Email>jcortez@example.com</Email>
				<Phone>878-241-8587</Phone>
				<BirthDate>1/18/1991</BirthDate>
				<JobTitle>Paediatric nurse</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Cameroon">
		<Organization OrganizationID="FEC51bce8421a7b">
			<Name>Roberson, Pennington and Palmer</Name>
			<Website>http://www.keith-fisher.com/</Website>
			<Description>Adaptive bi-directional hierarchy</Description>
			<Founded>1993</Founded>
			<Industry>Telecommunications</Industry>
			<NumberEmployees>5571</NumberEmployees>
			<Employees UserID="9F5DeD7aD228F5a">
				<FirstName>Beverly</FirstName>
				<LastName>Esparza</LastName>
				<Sex>Female</Sex>
				<Email>iphelps@example.net</Email>
				<Phone>327-578-8771</Phone>
				<BirthDate>12/9/1973</BirthDate>
				<JobTitle>Passenger transport manager</JobTitle>
			</Employees>
		</Organization>
	</Country>
	<Country name="Canada">
		<Organization OrganizationID="7b3fe6e7E72bFa4">
			<Name>Berg-Sparks</Name>
